### ISSUE TITLE
Integration test: check against devs

### ISSUE THREAD

**Issue by szabo137** [QEDjl-project/QED.jl#36]
There are situations for the integration test, where the package build of a dependent package depends by itself on a dev branch of another package. 

For instance, if we update `QEDbase.jl` to reflect certain changes in `QEDprocesses.jl#dev`, the integration tests in the `QEDbase.jl` PR will test against the `QEDprocesses.jl#dev` and become green if the unit tests pass. However, the integration tests in the `QEDbase.jl` PR will also test against `QEDevents.jl#dev` which depends on `QEDprocesses.jl#main` and not on `QEDprocesses.jl#dev`. Therefore, the integration tests against `QEDevents.jl#dev` will eventually fail. 

IDK how to solve this, but every integration test should set up the environment with all dev-versions of the dependent packages. This makes sure, that all tests pass if all downstream dev-branches are combined with the branch pending in the PR upstream.

**Comment by SimeonEhrig** [comment]
I'm working on it. It should also solve #33, because I need to construct the dependency graph an modify it.
